name: CI/CD Continuous deployment

on:
  workflow_dispatch: # trigger manual

jobs:
  build:

    name: Retrain model, package API, push Docker image to ECR and deploy to Lambda Function
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
          pip install -r requirements.txt

    - name: Run training_pipeline.py
      run: |
        python src/training_pipeline.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::193194117892:role/service-role/ml-cicd-testing-role-g3nc3y0o
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-custom-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ml-cicd-testing
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
    
    - name: Update aws custom lambda function code
      id: update-custom-function-code
      env:
        IMAGE_URI: ${{ steps.build-custom-image.outputs.image }}
      run: |
        aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:193194117892:function:ml-cicd-testing --image-uri $IMAGE_URI